development:
  adapter: mysql2
  encoding: utf8
  database: App42PaaS-Rails-MySQL-Sample_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2            
  host: 54.208.130.57                         # VM IP
  port: 64431                          # VM Port  
  database: demo_db             # Database Name
  username: aggy48qy0uz7xrnn                # User Name
  password: 'ay0ooox8slrm6uoa1arr7l4hzac6n3ge'             # Password


