development:
  adapter: mysql2
  encoding: utf8
  database: App42PaaS-Rails-MySQL-Sample_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2            
  host: 54.208.130.57                         # VM IP
  port: 48668                          # VM Port  
  database: demo_db             # Database Name
  username: a94xepztww52z4gr                # User Name
  password: 'atzzagmjxe428o4h9yartlexylcdh2rs'             # Password


