development:
  adapter: mysql2
  encoding: utf8
  database: App42PaaS-Rails-MySQL-Sample_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2            
  host: 54.208.130.57                         # VM IP
  port: 53653                          # VM Port  
  database: demo_db             # Database Name
  username: aqfjgj73vsnmddoi                # User Name
  password: 'acavceal34mvrqy3bry17bsain3gkw16'             # Password


